function Err = QOI_Algebraic_Equil_PerErr(params)
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here
alpha=params.alpha;
sigma=params.sigma;
gamma=params.gamma;

ApproxEquil=(-sigma.DV*(alpha.DV_DS*gamma.DR*(gamma.DV + alpha.DS_DV)...
    + alpha.DV_DR*(gamma.DS*(gamma.DV + alpha.DR_DV)...
    - alpha.DV_DS*(alpha.DS_DV + alpha.DR_DV))))...
    /(2*alpha.DV_DS*alpha.DV_DR*gamma.DV*(gamma.DV + alpha.DS_DV + alpha.DR_DV));
TrueEquil=ApproxEquil+sqrt(...
sigma.DS^2*sigma.DR^2*sigma.DV^2*...
(-4*alpha.DV_DS*alpha.DV_DR*(alpha.DV_DS + gamma.DS)*...
(alpha.DV_DR + gamma.DR)*gamma.DV*...
(gamma.DV+alpha.DS_DV+alpha.DR_DV)+...
(alpha.DV_DR*gamma.DS*(gamma.DV+alpha.DR_DV)...
+alpha.DV_DS*...
(gamma.DR*(gamma.DV+alpha.DS_DV)...
+alpha.DV_DR*(2*gamma.DV+alpha.DS_DV+alpha.DR_DV)))^2))/...
(2*alpha.DV_DS*alpha.DV_DR*sigma.DS*sigma.DR*gamma.DV*(gamma.DV + alpha.DS_DV + alpha.DR_DV));

Err=(ApproxEquil-TrueEquil)/(sigma.DV/gamma.DV);
end